### ISSUE TITLE
Can’t connect after reboot

### ISSUE THREAD

**Issue by grosdode** [mjwwit/node-red-contrib-ikea-tradfri#1]
Hello, 
first of all, thank you for work. My system is based on IOTSTACK (https://sensorsiot.github.io/IOTstack/) after I restart the node red container or reboot the PI your nodes aren’t able to connect to the bridge until I manually access the edit mode of the setup node and press update. I don’t have to do any changes, just hit the update button and deploy.

**Comment by mjwwit** [comment]
That's an interesting issue... I can't really say why that happening. I'm not familiar with IOTSTACK, but I'll see if I can get a test setup up and running when I find the time.

**Comment by grosdode** [comment]
If I can provide you more infromation, let me know.

**Comment by mjwwit** [comment]
I've just released a new version that improves error reporting. Can you check if an error is logged after restarting? This may shed some light on the underlying cause.

**Comment by grosdode** [comment]
Seems to work now
