### ISSUE TITLE
Switch control error messages in debug log

### ISSUE THREAD

**Issue by Soiski71** [mjwwit/node-red-contrib-ikea-tradfri#10]
Hi, I'm having similar issue as JBlond on getting the switch to accept the command. Actually it works ON/OF what ever code you send to it but gives annoying debug error. The light Control accepts to same code with out any issues.

Here the full message I send in inject.

6/24/2021, 9:55:28 PMnode: cf91895d.8001a8
msg : Object
object
_msgid: "30b3a0a4.a82e3"
payload: object
topic: array[1]
payload: "on"

Either I'm really simple and alone in the universe but I really could not figure the role of the topic number ? Should it actually refere to the payload.instanceId ref number or is it just a random number :)

Help much appriciated and hey EXCELLENT WORK !!

**Comment by mjwwit** [comment]
I'm afraid I'll need a bit more detail. The full message you mentioned contains objects which probably contain the problem. You can easily copy the full message (including nested objects) by clicking the copy button that appears when you hover over a debug message:
![image](https://user-images.githubusercontent.com/4455124/123389641-615b8600-d59a-11eb-96e8-4ec7007afc58.png)

The `topic` property in the message contains a list of `instanceId`s or `groupId`s. These are basically unique identifiers given to Tradfri devices and rooms that are connected to the gateway.

**Comment by Soiski71** [comment]
Here, Sorry thought I managed to get everything last time :)

{"_msgid":"660271a7.a073c","payload":{"topic":[1],"payload":"on"}}

Best Regards, Sami

**Comment by mjwwit** [comment]
I see the problem. You put the object specified in the documentation into the `payload` property of the message. The documentation is specifying the entire message though. You should update the nodes sending messages to the switch-control to look like this:

```diff
{
  "_msgid": "660271a7.a073c",
- "payload": {"topic": [1], "payload": "on"}
+ "topic": [1],
+ "payload": "on"
}
```

**Comment by Soiski71** [comment]
Hi Thanks:

Still with this I get 

{"_msgid":"3c58d8ed.b0b678","topic":"[1]","payload":"on"}

error:
Invalid message received, using node config!
Invalid value "[1]" supplied to : TradfriStateInputMessage/0: Partial<{ topic: (Int | Array<Int>) }>/topic: (Int | Array<Int>)/0: Int
Invalid value "[1]" supplied to : TradfriStateInputMessage/0: Partial<{ topic: (Int | Array<Int>) }>/topic: (Int | Array<Int>)/1: Array<Int>

Funnily enough I made a typo when writing the first time "topic" as "toepic" and that version does not give me any errors...
So actually sending only msg.payload ="on" does the trick with out error.

{"_msgid":"c5a54a2d.e3a798","payload":"on"}

**Comment by mjwwit** [comment]
You made a small error in your payload: you should be using `"topic": [1]` instead of `"topic": "[1]"`

**Comment by Soiski71** [comment]
Hi Michael,

Agree seems that Topic needs to be number format and payload text string.

What  is the function of the Topic here as it seems to work also without it ?
