### ISSUE TITLE
Did IKEA Home Smart 1.17.0 Update (Gateway 1.15.34) kill the GW connection - SOLVED With TEMP FIX

### ISSUE THREAD

**Issue by Soiski71** [mjwwit/node-red-contrib-ikea-tradfri#12]
Hi, Suddenly I lost all connection to IKEA GW. Might the update screw up something. Official APP still works but the connection to GW is lost and if trying to reconnect / authenticate I get this error

![image](https://user-images.githubusercontent.com/59532263/124025754-8405f880-d9f9-11eb-8124-b0db6bd61618.png)

Can anyone else confirm that their GW is working in the new 1.15.34 version ?

**Comment by mattes8612** [comment]
Hello, i have the same problem with gateway firmware 1.15.34. 

AlCalzone already workes on the issue. 

https://github.com/AlCalzone/node-tradfri-client/issues/517

I hope there will be a fix for node red soon…

**Comment by Soiski71** [comment]
Excellent,( I mean for once I did not screw up anything by my self :)

**Comment by Soiski71** [comment]
Seems that some sort of workaround has been able to implement.

https://github.com/AlCalzone/node-tradfri-client/issues/517

Michael, any ideas when you can import the fix ?

**Comment by tomgidden** [comment]
For what it's worth, I just did `npm install node-tradfri-client@3.0.1` in `node_modules/node-red-contrib-ikea-tradfri`, restarted Node-RED and _for my setup_ it works fine now.  That's not a comprehensive test by any stretch, but it does mean I'm no longer stuck in the dark. :)

**Comment by Soiski71** [comment]
Tom, Can you give the excat (command line) method you installed this update (in Linux... I asume) ?

I dont want to be testing :) as everything else works at the moment and not a guru in Linux/Ubuntu.

Thanks in advance.

**Comment by muleooo** [comment]
> For what it's worth, I just did `npm install node-tradfri-client@3.0.1` in `node_modules/node-red-contrib-ikea-tradfri`, restarted Node-RED and _for my setup_ it works fine now. That's not a comprehensive test by any stretch, but it does mean I'm no longer stuck in the dark. :)

![image](https://user-images.githubusercontent.com/2170565/124304250-b7649680-db63-11eb-85a4-2485d6885d86.png)
Worked for me, thanks 👍

**Comment by Soiski71** [comment]
Hmm.. So googled how to install to specif folder and found this. Run it ...but still the same issue. Node-Red restarted , did not work. Machine rebooted , still no change. 

npm install node-tradfri-client@3.0.1 --prefix node_modules/node-red-contrib-ikea-tradfri

Did you @muleooo or @tomgidden actually created a new gateway connection or used your old ones ? In my search for fix I deleted all my old connection and needed to now create a new one ...and still failing ?

How could one check that the update actually wnet through to correct place ( i.e what file to check at what location that it has 3.0.1 version now). Any ideas ?

**Comment by tomgidden** [comment]
@Soiski71 sorry, I was having a nap, so didn't see your message :)

For me, on an Ubuntu box:
```
cd ~/.node-red/node_modules/node-red-contrib-ikea-tradfri 
npm install node-tradfri-client@3.0.1
```
was enough

**Comment by muleooo** [comment]
use cd to change directory to that folder, then install
```
cd ~/.node-red/node_modules/node-red-contrib-ikea-tradfri
npm install node-tradfri-client@3.0.1
```

**Comment by Soiski71** [comment]
Excellent works now also for me !! Thank both Tom and mulee !!

Tom, Naps are excellent, Had mine also when waiting ... ;)

**Comment by muleooo** [comment]
Uhh I think you should leave this issue open, it's just a temporary fix

**Comment by Soiski71** [comment]
Agree :)

**Comment by mjwwit** [comment]
I'm terribly sorry for my late response, I've had a busy week... I will be releasing an update to fix this issue today.

**Comment by mjwwit** [comment]
I've just release version 0.4.7 which contains node-tradfri-client 3.0.1. It may take a bit before this update shows up in your Node-RED palette.
