### ISSUE TITLE
No status from tradfri since latest update 31-6-2021

### ISSUE THREAD

**Issue by EddyCapture** [mjwwit/node-red-contrib-ikea-tradfri#13]
My tradfri equipment automatically had the last update via the ikea bridge on 31-6-2021.
From that moment on I have no longer received the status of the connected lamps and plugs.
Everything that is on my Pi 3B+ has now been updated with the latest update. But unfortunately I still get the message: not connected. This is because the bridge is not seen. IP address and security code were correct, and have been re-entered. Unfortunately no positive result.

**Comment by mjwwit** [comment]
Are you running the latest version? (0.4.7)

**Comment by EddyCapture** [comment]
No. I am running version 0.4.5.
According to Node-Red UI: the latest version.
I am unfamiliar with installing a newer version other than through the UI.

**Comment by EddyCapture** [comment]
update:
installing v0.4.7 with lxterminal did not update the 0.4.5 version in node red.
So I did something wrong. Most likely the installation path was wrong.

**Comment by mjwwit** [comment]
I'm not sure where and how you're running Node-RED, but generally speaking it creates a working directory under a user home folder (`~/.node-red`). In this folder you'll find a file called `package.json`. This file lists all of the nodes installed through the palette. You'll find `node-red-contrib-ikea-tradfri` in there, probably with version `~0.4.5`. If you change this to `~0.4.7` and run `npm install` in this folder it will update to the new version. Afterwards you will need to restart Node-RED.

**Comment by My-Random-Thoughts** [comment]
Thanks, that worked for me.  Not sure why Node-RED is not picking up the update though.

**Comment by EddyCapture** [comment]
@mjwwit 
it took me a while to realize that .node-red was a hidden folder.
I already installed and uninstalled something incorrectly. Unfortunately with error messages. During this install and uninstall I made quite a mess of it. Removing nodes via Palette was also no longer possible.
So I am forced to reinstall everything.
Unfortunately.
Would be nice if you can still manage to update the ikea node via the palette.

**Comment by mjwwit** [comment]
> Would be nice if you can still manage to update the ikea node via the palette.

This would indeed be nice, I don't know what else I can do to speed this up though... I'm glad you got it working though. I'll close this ticket now.
