### ISSUE TITLE
bulb power value always says "Internal Battery"

### ISSUE THREAD

**Issue by My-Random-Thoughts** [mjwwit/node-red-contrib-ikea-tradfri#14]
Hello, not sure if this is correct or not, but my IKEA light bulb always has a payload/power value of "Internal Battery" whether it's on/off or unpowered (off a mains).  Is this correct?

I am trying to see if I can detect if a light has been turned off at the mains rather than just simple turned off.
Some data, if it helps....

```
    "firmwareVersion": "2.3.050",
    "manufacturer": "IKEA of Sweden",
    "modelNumber": "TRADFRI bulb E27 WW 806lm",
    "power": "InternalBattery",
    "otaImageType": 16643,

```

Thanks

**Comment by mjwwit** [comment]
I've noticed this as well. I think `InternalBattery` refers to an internal and unknown power source. I'm not sure if this is a translation issue in the tradfri library I use or if the gateway uses this value. In any case this is nothing to worry about.
