### ISSUE TITLE
Installing 0.4.7 installs 0.4.5

### ISSUE THREAD

**Issue by DAveShillito** [mjwwit/node-red-contrib-ikea-tradfri#15]
I'm not sure if this is an issue with my Node-RED Install, or a configuration issue here.
I'm posting it here in case it is the latter, but feel free to close it if you think it is the former.

If I search for node-red-contrib-ikea-tradfri in the pallet manager it says 0.4.7 is available.

![image](https://user-images.githubusercontent.com/25068347/125690798-d349b37d-d494-4cec-a079-ae4bad73bec9.png)

I press install and it appears to install, but when it has installed it says the version is 0.4.5.

![image](https://user-images.githubusercontent.com/25068347/125691000-ed502134-19ee-4387-8ed0-2068f476f010.png)

This still has the configuration issue, so I'm assuming it is 0.4.5.

I have removed it and and tried to reinstall it a few times over the last few days, but always have the same issue.

**Comment by mjwwit** [comment]
Node-RED is a bit slow with recognizing updates. You will see when the update is available if the "Nodes" tab lists the update. The "Install" tab is not used for updating, only for adding new nodes.
If you really want the update right now, you can always update it manually by going to your Node-RED working directory (usually `~/.node-red`), changing the version in the `package.json` file, and then running `npm install`.

**Comment by DAveShillito** [comment]
Thanks cool, I was confused that the two panes seemed to show different versions.
I shall either wait or attempt the manual update you suggested.
Thanks very much :)
