### ISSUE TITLE
Switching lights on and off

### ISSUE THREAD

**Issue by ahartman** [mjwwit/node-red-contrib-ikea-tradfri#16]
I am using your code reliably to set color temperature and/or brightness for white-spectrum bulbs, no problems here.

However, I am having huge problems in switching lights on or off.

1. With syntax 'isOn', I can switch lights off but not on. In attached image 1 , the first 'off' message works, the second 'on' messages has no effect.
2. With syntax 'payload' : 'on' (or 'off'), I get an error message, see attached image 2.
3. 
I hope you can help me out.
Regards, ahartman, Belgium

<img width="385" alt="image 1" src="https://user-images.githubusercontent.com/688316/128628639-a15aa816-15b5-496e-b962-9bf3722754c7.png">

<img width="680" alt="image 2" src="https://user-images.githubusercontent.com/688316/128628643-7d61f5dc-1350-4c9a-bc54-806fa0c4e0bf.png">

**Comment by ChristophA** [comment]
To switch the lights on and of I'm using a JSON formatted payload.
For on:
`{
    "onOff": true
}`
For off:
`{
    "onOff": false
}`

**Comment by ahartman** [comment]
Dear mjwwit,

From time to time, I see the error in the attached screen image. As you can see the message sent to your node is good and contains valid Tradfri IDs. There seems to be no pattern as to when this shows up; it looks to happen more when I am working on the Node Red code and lots of messages get sent to Tradfri.

Any leads?
Regards, ahartman, belgium

<img width="510" alt="Schermafbeelding 2021-10-11 om 06 55 56" src="https://user-images.githubusercontent.com/688316/136738674-61906af1-6dbc-482b-bfe3-7362b3375ddd.png">

**Comment by mjwwit** [comment]
> I found out when the error message 'invalid message' comes up. When you specify a fully defined control node, you only need to send 'something' to kick it into action, no need to specify a topic with IDs or a payload with JSON. That leads to the error message. So, the node still wants to receive a 'valid' message although it does not need any information in there.

The way this node works is that it combines the details you enter in the configuration with the details from the message is receives. This allows you to either configure the devices you want to control in the node, or dynamically control them in the message you send to the node.
If, however, you don't configure anything in the node and your message also doesn't specify anything properly, the node does not know what to do.

So this is what's going on (from what I can see in the error message):

1. The node receives a message that does it does not understand. In this case it's expecting either a number or a list of numbers in the message `topic`, but instead it's receiving a list with 2 empty bits of text (`""`).
2. The node makes note of this by letting you know in the debug log (this is the error you see)
3. The node tries to default to what you've configured in the node configuration. However, if you haven't configured anything there it will end up doing nothing.

If you want to get rid of this error message you will need to ensure that the messages your send match the requirements. The node documentation displays what it's expecting and where.

**Comment by ahartman** [comment]
As you can see in the attached screen image, I specified a group and the action ‘on’. If I understand correctly, there does not to be any additional information in the incoming msg; the node should know what to do and not send an error in my opinion or do i have this wrong?

Regards, ahartman

**Comment by mjwwit** [comment]
Your not entirely wrong. In the situation you're describing the node will give an error, but the action will still be applied properly to the configured lights.

If you want to fix the error you need to make sure that all messages you send to the node match the requirements. In this specific case you can solve the issue by removing `topic` from the messages (since you've already configured which lights need to be controlled).

**Comment by mjwwit** [comment]
I've just released a new version (0.6.0) which includes checkboxes for every node so you can disable these message validation warning logs.

**Comment by ahartman** [comment]
Thank you.
I will install it and see what it does.

Regards, ahartman, belgium
