### ISSUE TITLE
Version 4.8 not available on NodeRed

### ISSUE THREAD

**Issue by DKAndreas** [mjwwit/node-red-contrib-ikea-tradfri#17]
Version 4.8 is not available on NodeRed ? 

Im not aware if I should state it as an “Issue”…

**Comment by mjwwit** [comment]
It is an issue, so you it's good you've reported it here. I'm not sure how to fix this however, but I'll try contacting Node-RED devs to see if they know the solution.
Meanwhile, if you're only a little bit comfortable in a terminal it's quite easy to manually update the version. You'll need to find your Node-RED working directory (usually `~/.node-red`). In that directory you'll find a `package.json` file. This file contains all of the installed nodes packages and their versions. Just find `node-red-contrib-ikea-tradfri` and update the version number next to it. Save this file and exit your editor. Afterwards just run `npm install` while still in the working directory and then restart Node-RED.

**Comment by DKAndreas** [comment]
Thank you very much for the feedback ! 👍 

Okay great! Lets see what they respond.

I have already installed the version 0.4.8 from the “backend” - works like a charm :-)
Thank you for the guide though!
But proper node-red installation would be ideal :-)

**Comment by mjwwit** [comment]
I figured out how to get Node-RED to show updates, I need to re-register the node every time I release an update :man_facepalming:...
I've just tested this with the freshly released 0.5.0, and it's already showing up for me!
