### ISSUE TITLE
Tradfri monitor node

### ISSUE THREAD

**Issue by ahartman** [mjwwit/node-red-contrib-ikea-tradfri#18]
I would presume this node fires at all changes in Tradfri, for example, when someone dims a light or switch es a light on. It does not do that. It seems to fire only at a Node Red restart. Using version 0.4.8.

**Comment by DKAndreas** [comment]
I have version 0.4.8, and it works perfectly for me. The monitor node gives an output every time a light/plug/curtain changes (I have approx 53 units connected).

Is youre Node-red updated to latest version (V2.0.5)?
Is youre IKEA gateway updated to latest version ?

**Comment by ahartman** [comment]
Yes, using latest versions.
I deleted the Tradfri module and reinstalled it. That solved the problem for now, keep fingers crossed.
