### ISSUE TITLE
Config node won't save properties

### ISSUE THREAD

**Issue by SpareSimian** [mjwwit/node-red-contrib-ikea-tradfri#24]
Version is 0.6.0.

I'm trying to set up a single outlet (switch). I create a new config node and fill in the node name, hostname (which I can ping) and key. I left the coap path and user/psk blank. (I also tried filling these in from known-working values.) I click the Update button and I'm returned to the switch config. I click the pencil button again to re-enter the config node editor and all the values except the node's name are blank. 

I'm able to talk to the hub with the latest version of libcoap's coap-client. I'm using CentOS 8 and libcoap-4.3.0.

Node-RED console output:
```
29 Dec 00:11:24 - [info] Starting flows
29 Dec 00:11:24 - [error] [tradfri-config:a1c093c7a6c5adc4] Error: The hostname must be a string.
29 Dec 00:11:24 - [error] [tradfri-switch-control:665350874c1c7380] TypeError: Cannot read properties of null (reading 'client')
29 Dec 00:11:24 - [info] Started flows
29 Dec 00:11:54 - [warn] Unable to find tradfri-config node "a1c093c7a6c5adc4"
29 Dec 00:11:54 - [warn] Unable to find tradfri-config node "a1c093c7a6c5adc4"
```

**Comment by mjwwit** [comment]
Are you sure you're using `node-red-contrib-ikea-tradfri`, and not another Tradfri plugin? This plugin does not have a configurable "coap path" in the config node.

**Comment by SpareSimian** [comment]
How strange. It's working today. I suspect something was cached from my previous installation of the old node-red-contrib-tradfri. (I'd tripped across this whole ecosystem when this 2017 video appeared in my Google news feed that introduced me to Node-RED. https://www.youtube.com/watch?v=wS8Vj0ba4ic ) Sorry for the confusion.
