### ISSUE TITLE
Multiple gateways - failing monitor

### ISSUE THREAD

**Issue by mdrda** [mjwwit/node-red-contrib-ikea-tradfri#3]
When two gateways are added only one produces monitor output and the other one is silent, except from initial output after new deployment. Seems it's the one added last which works. State works fine for both.

**Comment by mjwwit** [comment]
Do you mean you added 2 config nodes? Or do you have to separate hardware gateways in your network?

**Comment by michal-mike** [comment]
Two hardware gateways each having its own config node within one Node-RED instance.

**Comment by mjwwit** [comment]
This will be hard to test for me, as I only have access to a single gateway, but I will do my best to locate and fix any problems that might cause this behavior.

**Comment by sigxcpu76** [comment]
For me both status and monitor fail on the second gateway. What's more interesting is that they've worked at some point but I cannot make them work after many restarts.

**Comment by mjwwit** [comment]
I don't have the time to support a project that I'm no longer using. I am therefore closing this issue.
