### ISSUE TITLE
tradfri-light-control: repeated devices listing in "Light(s)" and random light on/off

### ISSUE THREAD

**Issue by drublin** [mjwwit/node-red-contrib-ikea-tradfri#30]
For some reason, devices listed in "Light(s)" list are repeated three times. "None" item is also repeated.

Though not sure if it's a Node or Node-Red issue.

I attach a screenshot. Here for demonstration i Selected all the lights in the node. I have only 92 lights.

92x3+3(none's) = 279

![image](https://user-images.githubusercontent.com/102928430/211832974-dbcb4c37-8d24-408f-844c-3286a7de0252.png)

Thank you for this Tradfri contribution! 

UPD: wanted to add a new issue, but they seem related.
A timer is used to trigger TRADFRI night lights ON and OFF. But they get randomly ON/OFF during the day, although the Big Timer always sends "onOff:false" to the tradfri-light-control node.

After some debugging, it seems that due to the above triple listing issue, the tradfri node also sends the update message to Gateway three times. But they **sometimes** differ.

Here the node has a static config for only one light named "C9.1". Timer sends OFF command every minute. The node sends three messages to gateway, but the second message sometimes differ, and this defines the light behavior. 

1st message is input from the Timer node.
2-4 are outputs (repeaded) to gateway
![image](https://user-images.githubusercontent.com/102928430/211844340-1db5d852-4c9a-4674-a823-a0fee29e6055.png)

any ideas?

**Comment by mjwwit** [comment]
I don't have the time to support a project that I'm no longer using. I am therefore closing this issue.
