### ISSUE TITLE
possibility to control the blinds

### ISSUE THREAD

**Issue by conderstal** [mjwwit/node-red-contrib-ikea-tradfri#9]
Hello,

I'm about to buy the ikea blinds but want to be sure I can control them via domoticz / nodered. I saw the state of the blinds can be checked but is it also possible to control the blinds?

**Comment by mjwwit** [comment]
The underlying library used by this project does offer methods to set blind position and to stop their movement, is that all you need? Sadly I don't have any IKEA blinds myself, so I'm not able to test this for you. I cannot find a distinct device type for them though, so I wonder what they will show up as...

Either way it may be that I'll need to expose these methods to a new Node-RED node. If you end up buying them I may need your help to make sure I get the implementation right.

**Comment by conderstal** [comment]
That sounds like a plan! I'll have to wait for the final verdict of my wife and let you know ;)

**Comment by DKAndreas** [comment]
I have IKEA curtains and it is unfortunately not working :-(

Curtain is representative in “tradfri monitor” - nice 👍 
However, it is not visible nor controllable in “tradfri-light-control” and “tradfri-switch-control”
:-( 👎 

I am using Version 0.4.8.
It could be great if you managed to get it to work :-)

**Comment by mjwwit** [comment]
I'm currently on vacation, but I'll start on this after I get back. I'll let you know if I need anything further when I get going.

**Comment by mjwwit** [comment]
I've just release version 0.5.0 with a new node to control blinds! Let me know if this is working, as I don't have any blinds to test this on myself.

**Comment by smartinick** [comment]
> I've just release version 0.5.0 with a new node to control blinds! Let me know if this is working, as I don't have any blinds to test this on myself.

Quick Test - Works for me - at least the "set position" command, didn't test anything else!

**Comment by smartinick** [comment]
operation - stop also works
as well as the status node seems to be 100% complete for blinds, including position,...

**Comment by mjwwit** [comment]
Alright then! Sounds like I can close this issue :smiley:
